.idea/.name
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
app/src/main/java/co/gobd/tracker/service/LocationService.java
app/src/main/java/co/gobd/tracker/ui/MainActivity.java

Now app checks if location is enabled or not. If enabled it does nothing. Sends location to server but if disabled it prompts user to enable location.

GFETCH-78 added location enable/disable check

---

app/src/main/AndroidManifest.xml
app/src/main/java/co/gobd/tracker/callback/LoginCallback.java
app/src/main/java/co/gobd/tracker/callback/TokenCallback.java
app/src/main/java/co/gobd/tracker/network/AuthApi.java
app/src/main/java/co/gobd/tracker/network/AuthClient.java
app/src/main/java/co/gobd/tracker/network/TrackerApi.java
app/src/main/java/co/gobd/tracker/service/LocationService.java
app/src/main/java/co/gobd/tracker/service/LoginService.java
app/src/main/java/co/gobd/tracker/service/TokenService.java
app/src/main/java/co/gobd/tracker/service/TrackerService.java
app/src/main/java/co/gobd/tracker/ui/LoginActivity.java
app/src/main/java/co/gobd/tracker/ui/MainActivity.java
app/src/main/java/co/gobd/tracker/utility/Constant.java
app/src/main/java/co/gobd/tracker/utility/SessionManager.java
app/src/main/java/co/gobd/tracker/utility/SharedPreferenceConstant.java
gradle/wrapper/gradle-wrapper.properties

- Merged master with GFETCH-110
- Fixed conflicts
- SessionManager works
- Dependency Injection integration works successfully

Merging GFETCH-110-Temp to GFETCH-110

---

app/build.gradle
app/src/main/java/co/gobd/tracker/config/BackendUrl.java
app/src/main/java/co/gobd/tracker/model/job/AssignedJob.java
app/src/main/java/co/gobd/tracker/model/job/JobModel.java
app/src/main/java/co/gobd/tracker/model/job/Location.java
app/src/main/java/co/gobd/tracker/model/job/Point.java
app/src/main/java/co/gobd/tracker/model/job/task/DeliveryTask.java
app/src/main/java/co/gobd/tracker/model/job/task/FetchDeliveryManTask.java
app/src/main/java/co/gobd/tracker/model/job/task/JobTask.java
app/src/main/java/co/gobd/tracker/model/job/task/PackagePickupTask.java
app/src/main/java/co/gobd/tracker/service/job/JobServiceImpl.java
app/src/main/java/co/gobd/tracker/ui/activity/JobActivity.java

AssignedJob is parsed through custom deserializer.

Fixes JSON parsing of AssignedJob for an Asset

---

app/build.gradle
app/src/main/java/co/gobd/tracker/ui/activity/MainActivity.java
app/src/main/java/co/gobd/tracker/utility/ServiceUtility.java
app/src/main/res/values/strings.xml

- Google Play Service checking now integrated

Fixes GFETCH-122

---

app/src/main/java/co/gobd/tracker/ui/activity/MainActivity.java
app/src/main/java/co/gobd/tracker/utility/SessionManager.java
app/src/main/java/co/gobd/tracker/utility/SessionManagerImpl.java
app/src/main/res/layout/activity_main.xml

Gfetch 128

---

app/src/main/java/co/gobd/tracker/ui/activity/MainActivity.java

adds stopLocationService() on onSignOutButtonClick()

Gfetch - 129

---

app/src/main/java/co/gobd/tracker/ui/service/LocationService.java

fixes service auto turnoff issue

Gfetch 130

---

app/src/main/java/co/gobd/tracker/ui/fragment/MapFragment.java

- map now shows pickup and delivery location

GFETCH-149

---

app/build.gradle
app/src/main/java/co/gobd/tracker/di/module/ApiModule.java
app/src/main/java/co/gobd/tracker/model/job/JobModel.java
app/src/main/java/co/gobd/tracker/model/job/Profile.java
app/src/main/java/co/gobd/tracker/model/job/User.java
app/src/main/java/co/gobd/tracker/model/job/order/Order.java
app/src/main/java/co/gobd/tracker/model/job/order/OrderCart.java
app/src/main/java/co/gobd/tracker/model/job/order/PackageList.java
app/src/main/java/co/gobd/tracker/model/user/Profile.java
app/src/main/java/co/gobd/tracker/ui/activity/MainActivity.java
app/src/main/java/co/gobd/tracker/utility/deserializer/JobModelDeserializer.java
app/src/main/java/co/gobd/tracker/utility/deserializer/LocationDeserializer.java
app/src/main/java/co/gobd/tracker/utility/deserializer/OrderCartDeserializer.java
app/src/main/java/co/gobd/tracker/utility/deserializer/OrderDeserializer.java
app/src/main/java/co/gobd/tracker/utility/deserializer/ProfileDeserializer.java
app/src/main/java/co/gobd/tracker/utility/deserializer/UserDeserializer.java
app/src/main/res/layout/activity_main.xml
app/src/test/java/co/gobd/tracker/utility/deserializer/JobModelDeserializerTest.java
app/src/test/java/co/gobd/tracker/utility/deserializer/OrderCartDeserializerTest.java
app/src/test/java/co/gobd/tracker/utility/deserializer/OrderDeserializerTest.java
app/src/test/java/co/gobd/tracker/utility/deserializer/ProfileDeserializerTest.java
app/src/test/java/co/gobd/tracker/utility/deserializer/UserDeserializerTest.java

- adds test for JobModelDeserializer, OrderCartDeserializer, OrderDeserializer, ProfileDeserializer, UserDeserializer

Gfetch 154

---

app/src/main/java/co/gobd/tracker/model/job/order/Order.java
app/src/main/java/co/gobd/tracker/utility/deserializer/OrderDeserializer.java
app/src/main/java/co/gobd/tracker/utility/deserializer/ProfileDeserializer.java

- fixes some minor POJO changes
- adds null check

fixes json serilization

---

app/src/main/java/co/gobd/tracker/model/job/Profile.java
app/src/main/java/co/gobd/tracker/utility/deserializer/ProfileDeserializer.java
app/src/test/java/co/gobd/tracker/utility/deserializer/ProfileDeserializerTest.java

- fixes pojo change in the backend
- changes ProfileDeserializer, Profile
- changes the test code for ProfileDeserializer

profile-pojo-fix

---

app/src/main/java/co/gobd/tracker/adapter/JobAdapter.java
app/src/main/res/layout/job_list_row.xml

- adds card view to show job list
- updates SHA1 hash for map

adds cardview to existing recyclerview

---

app/src/main/java/co/gobd/tracker/model/job/Location.java
app/src/main/java/co/gobd/tracker/utility/deserializer/JobModelDeserializer.java
app/src/main/java/co/gobd/tracker/utility/deserializer/LocationDeserializer.java
app/src/main/java/co/gobd/tracker/utility/deserializer/OrderDeserializer.java

- adds locality field on location model

GFETCH-200 adds locality field in location model

---

app/src/main/java/co/gobd/tracker/adapter/JobAdapter.java
app/src/main/java/co/gobd/tracker/di/module/AppModule.java
app/src/main/java/co/gobd/tracker/network/JobApi.java
app/src/main/java/co/gobd/tracker/presenter/MainPresenter.java
app/src/main/java/co/gobd/tracker/service/job/JobService.java
app/src/main/java/co/gobd/tracker/service/job/JobServiceImpl.java
app/src/main/java/co/gobd/tracker/ui/activity/MainActivity.java
app/src/main/java/co/gobd/tracker/ui/view/MainView.java
app/src/main/java/co/gobd/tracker/utility/Constant.java

**What has been done**
- Refactored MainActivity to use MVP
- Added state parameter in getAssignedJobList() so we can use this method to download jobs based on state like "IN_PROGRESS", "CANCELLED", "COMPLETED".

GFETCH-202 Ability to download Jobs based on state

---

.travis.yml
app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/co/gobd/tracker/adapter/JobAdapter.java
app/src/main/java/co/gobd/tracker/adapter/OnTaskUpdateClickListener.java
app/src/main/java/co/gobd/tracker/model/job/UpdateTaskState.java
app/src/main/java/co/gobd/tracker/network/JobApi.java
app/src/main/java/co/gobd/tracker/presenter/MainPresenter.java
app/src/main/java/co/gobd/tracker/service/job/JobService.java
app/src/main/java/co/gobd/tracker/service/job/JobServiceImpl.java
app/src/main/java/co/gobd/tracker/ui/activity/MainActivity.java
app/src/main/java/co/gobd/tracker/ui/view/MainView.java
app/src/main/java/co/gobd/tracker/utility/Constant.java
app/src/main/java/co/gobd/tracker/utility/deserializer/JobModelDeserializer.java
app/src/main/java/co/gobd/tracker/utility/deserializer/UserDeserializer.java
app/src/main/res/layout/layout_task_update.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

- Job task (Pickup and Delivery) can be updated individually
- Main Activity and all its data are retained if the screen rotates
- Job details activity does not create a new instance of Main Activity if the back arrow button is pressed from the Toolbar. Instead, it goes back to the MainActivity (launch mode = singleTop)
- `CALL` button is not yet implemented (WIP)
- `OPEN IN MAP` is not yet implemented (WIP in GFETCH-201)

GFETCH-204 Task update capability 

---

app/src/main/java/co/gobd/tracker/model/job/JobModel.java
app/src/main/java/co/gobd/tracker/utility/deserializer/JobModelDeserializer.java
app/src/main/java/co/gobd/tracker/utility/deserializer/OrderDeserializer.java

1.  Adds new field in JobModel and modifies JobModelDeserializer according to POJO.
2. Updates JSON field name.

Pojo hotfix

---

app/src/main/java/co/gobd/tracker/presenter/MainPresenter.java
app/src/main/java/co/gobd/tracker/ui/activity/MainActivity.java
app/src/main/java/co/gobd/tracker/ui/view/MainView.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/layout_main.xml

- adds swipe refresh layout to refresh job list

adds swipe refresh layout to refresh job list

---

app/src/main/java/co/gobd/tracker/adapter/JobAdapter.java
app/src/main/java/co/gobd/tracker/ui/activity/MainActivity.java

- adds dialler to call customer manager

GFETCH-205

---

app/src/dev/java/co/gobd/tracker/config/BackendUrl.java
app/src/prod/java/co.gobd.tracker/config/BackendUrl.java

-points dev server to _http://fetchdev.gobd.co_ from _http://taskcatdev.azurewebsites.net_
-points prod server to _http://fetchprod.gobd.co_ from _http://gofetch.cloudapp.net_

GFETCH-230 : changes BASE URL

---

app/src/main/java/co/gobd/tracker/ui/activity/LoginActivity.java

- adds finish() in LoginActivity to fix back button press bug issue

GFETCH-248

---

README.md

- Adds description
- Adds screenshot of the app

GFETCH-273
